#!/usr/bin/env bash
# Reject staged files under packages/<pkg>/dist/. These are build outputs
# regenerated by `npm run build` (and `prepublishOnly` at publish time);
# committing them causes the recurring src/dist drift surfaced in Sprint 39.
set -euo pipefail

if [ "$#" -eq 0 ]; then
  exit 0
fi

printf 'Refusing to commit MCP package dist/ files (build output, not source):\n' >&2
for f in "$@"; do
  printf '  %s\n' "$f" >&2
done
printf '\nUnstage with:\n  git reset HEAD -- %s\n' "$1" >&2
printf '\nIf you genuinely need to commit a dist/ artifact, bypass with:\n  git commit --no-verify\n' >&2
exit 1
